### ISSUE TITLE
Hi，DIYgod ，该项目没有说明如何贡献ip

### ISSUE THREAD

**Issue by jmpcyc** [DIYgod/EasyGoAgent#1]
RT

**Comment by DIYgod** [comment]
博客留言即可: www.anotherhome.net/1727  但请确保IP质量较高 ღ(๑╯◡╰๑ღ)

**Comment by skyline75489** [comment]
这样公开的IP越多，被封杀的IP也就越多啊。。。

**Comment by DIYgod** [comment]
IP全部来自GoGo Tester, 都是半公开状态的, 真想封的话早就封光了, 另外如果该项目被盯上我会停止更新或想其他办法的

**Comment by icicle198514** [comment]
我认为封禁IP的方式并不好。政府不应该限制互联网，因为只有未成年人限制网络是最好的。

**Comment by icicle198514** [comment]
在他们的回复帖子里有的，很久以前我看到好多用到死的appid.

On October 14, 2015 6:22:38 PM GMT+08:00, Wenjie Fan notifications@github.com wrote:

> Closed #1.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/DIYgod/EasyGoAgent/issues/1#event-435042210

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
